---
allowedOrigins:
  - http://localhost:3000
  - http://localhost:3001
  - http://localhost:5000
  - https://zeus.safeplaces.extremesolution.com
  - https://hermes.safeplaces.extremesolution.com
  - https://safeplaces.extremesolution.com
  - http://e05a05b038bf.ngrok.io