version: '3'
services:
  safeplaces:
    build:
      context: .
    container_name: safeplaces
    #restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - safeplace
    depends_on:
      - db
  db:
    image: postgres:12.1
    container_name: database
    env_file:
      - .database.env
    volumes:
      - dbdata:/var/lib/postgresql/data/
    ports:
      - "5432"
    networks:
      - safeplace
networks:
  safeplace:
     driver: bridge

volumes:
  dbdata:
  node_modules:  
