openapi: 3.0.0
info:
  title: Safe Places - Server Backend
  description: >-
    API spec for SAFE PLACES Backend as part of the SAFE PATHS initiative.  You
    can find out more about SAFE PATHS AT
    [https://covidsafepaths.org/](https://covidsafepaths.org/)
  version: 1.0.0
  contact:
    email: satoshi.kawase@pathcheck.org
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: /v1
components:
  securitySchemes:
    contactTracer:
      type: http
      scheme: bearer
      description: contact tracer access
    admin:
      type: http
      scheme: bearer
      description: admin access
  responses:
    UnauthorizedError:
      description: Lacks sufficient authority for operation
    InvalidRequest:
      description: Invalid request
    InternalServerError:
      description: Internal Server Error
    AccessForbidden:
      description: Access forbidden
    NotFound:
      description: Not Found
    InvalidToken:
      description: "There is no user with the username or the password does not match."
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid credentials"
  parameters:
    authCodeParam:
      in : path
      name: code
      required: true
      description: 'Access code'
      schema:
        $ref: '#/components/schemas/authCode'
    caseIdParam:
      in : path
      name: caseId
      required : true
      description: 'The ID of the case'
      schema:
        $ref: '#/components/schemas/caseId'
    orgIdParam:
      in : path
      name: orgId
      required: true
      description: 'the ID of the org'
      schema:
        $ref: '#/components/schemas/orgId'
    pointIdParam:
      in : path
      name: pointId
      required: true
      description: 'The Id of the point'
      schema:
        $ref: '#/components/schemas/pointId'
  schemas:
    apiEndpoint:
      type: string
      example: https://s3.aws.com/bucket_name/safepaths.json
    authCode:
      type: string
      example: bluebird
    caseId:
      type: number
      example: 23432461
    caseState:
      type: string
      enum:
        - original
        - unpublished
        - staging
        - published
    case:
      type : object
      properties:
        id:
          type: integer
          example: 14
        updatedAt:
          $ref : '#/components/schemas/timeString'
        status:
          $ref: '#/components/schemas/caseState'
        expiresAt:
          $ref : '#/components/schemas/timeString'
    caseCreation:
      type : object
      properties:
        caseId:
          type: integer
          example: 14
        updatedAt:
          $ref : '#/components/schemas/timeString'
        status:
          $ref: '#/components/schemas/caseState'
        expiresAt:
          $ref : '#/components/schemas/timeString'
        authCode:
          $ref: '#/components/schemas/authCode'
    cases:
      type: array
      items:
        $ref: '#/components/schemas/case'
    concernPointDBAdd:
      type: object
      properties:
        longitude: 
          type : number
          example: 14.91328448
        latitude:
          type : number
          example: 41.24060321
        time : 
          $ref : '#/components/schemas/timeString'
    concernPointDb:
      type: object
      properties:
        pointId:
          type: number
          example: 12
        longitude: 
          type : number
          example: 14.91328448
        latitude:
          type : number
          example: 41.24060321
        time : 
          type : string
          example: "2020-05-30T18:25:43.511Z"
    concernPointApp: 
      type: object
      properties:
        longitude:
          type: number
          example: 14.91328448
        latitude:
          type: number
          example: 41.24060321
        time:
          type: number
          example: 1589117739000
        hash:
          type: string
          example: 87e916850d4def3c
    concernPoints:
      type: array
      items:
        $ref: '#/components/schemas/concernPointApp'
    consent:
      type: object
      properties:
        consent : 
          type: boolean
          example: true
        accessCode:
          $ref : '#/components/schemas/authCode'
    coordinates:
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
    informationWebsiteUrl:
      type: string
      example: "http://cdc.gov"
    orgId:
      type: number
      example: 32424552
    orgName:
      type: string
      example: "Same Health Authority"
    orgConfiguration:
      type: object
      properties:
        organizationId:
          $ref: '#/components/schemas/orgId'
        name:
          $ref: '#/components/schemas/orgName'
        notificationThresholdPercent:
          $ref: '#/components/schemas/notificationThreshold'
        notificationThresholdCount:
          $ref: '#/components/schemas/notificationCount'
        numberofDaysToRetainRecords:
          $ref: '#/components/schemas/numberOfDaysToRetainRecords'
        regionCoordinates:
          $ref: '#/components/schemas/regionCoordinates'
        apiEndpoint:
          $ref: '#/components/schemas/apiEndpoint'
        referenceWebsiteUrl:
          $ref: '#/components/schemas/referenceWebsiteUrl'
        informationWebsiteUrl:
          $ref: '#/components/schemas/informationWebsiteUrl'
    notificationCount:
      type: number
      example: 6
    notificationThreshold:
      type: number
      example: 66
    numberOfDaysToRetainRecords:
      type: number
      example: 14
    pointId:
      type: integer
      example: 212
    referenceWebsiteUrl:
      type: string
      example: "http://cdc.gov"
    regionCoordinates:
      type: object
      properties:
        ne:
          $ref: '#/components/schemas/coordinates'
        sw:
          $ref: '#/components/schemas/coordinates'
      example:
        value:
          { "ne": { "latitude": 20.312764055951195, "longitude": -70.45445121262883}, 
            "sw": { "latitude": 17.766025040122642, "longitude": -75.49442923997258}
          }
    timeString:
      type: string
      example: "2020-05-30T18:25:43.511Z"
    token: 
      type: object
      properties:
        token:
          type: string
          example: "eyABCD4321JIUzI1NiIsInR5cCI6IkpXVCJ9"
    valid:
      type: object
      properties:
        valid : 
          type: boolean
          example: true
    login:
      type: object
      properties:
        username:
          type: string
          example: "admin"
        password:
          type: string
          example: "admin"
  examples:
    concernPoints:
      value: {  
                "concernPoints" : 
              [  {"pointId": 232, "time":"2020-05-30T18:25:43.511Z","longitude":-0.10753902581515137,"latitude":51.55987524514395},
                {"pointId": 233, "time":"2020-05-30T18:25:43.511Z","longitude":-0.06407687379643874,"latitude":51.53626227398831},
                {"pointId": 234, "time":"2020-05-30T18:25:43.511Z","longitude":-0.10383699531844902,"latitude":51.5687569927817},
                {"pointId": 235, "time":"2020-05-30T18:25:43.511Z","longitude":-0.09565287120047716,"latitude":51.56663238135933},
                {"pointId": 236, "time":"2020-05-30T18:25:43.511Z","longitude":-0.13367363946595986,"latitude":51.53989797636888},
                {"pointId": 237, "time":"2020-05-30T18:25:43.511Z","longitude":-0.05729357699158614,"latitude":51.53321925729781},
                {"pointId": 238, "time":"2020-05-30T18:25:43.511Z","longitude":-0.054365847106010994,"latitude":51.550572004199395},
                {"pointId": 239, "time":"2020-05-30T18:25:43.511Z","longitude":-0.12014169804782877,"latitude":51.54859663929235}
              ]}
    casesList:
      value: 
        {
          "cases": [
                    {
                      "caseId": 12,
                      "updatedAt": "2020-05-21T18:25:43.511Z",
                      "status": "unpublished",
                      "expiresAt": "2020-05-30T18:25:43.511Z"
                    },
                    {
                      "caseId": 13,
                      "updatedAt": "2020-05-21T18:25:43.511Z",
                      "status": "staging",
                      "expiresAt": "2020-05-30T18:25:43.511Z"
                    },
                    {
                      "caseId": 14,
                      "updatedAt": "2020-05-21T18:25:43.511Z",
                      "status": "published",
                      "expiresAt": "2020-05-30T18:25:43.511Z"
                    }
                  ]
        }
paths:
  '/access-code/valid':
    get:
      summary: Determines whether an access code is valid and if it can be used to perform an `/upload` API call
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accessCode : 
                  $ref : '#/components/schemas/authCode'
      responses:
        '200':
          description: Successful Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/valid'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError' 
  /consent:
    post:
      summary: Logs user consent to health authority’s terms of service. Invalidates the accessCode that is passed in the payload if  consent  is false.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/consent'
      responses:
        '200':
          description: Successful request
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError' 
  /upload:
    post:
      summary: Accepts SAFE PATHS data upload from the user. Access code sent in body must match access code created in /case/access-code call.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accessCode:
                  $ref: '#/components/schemas/authCode'
                concernPoints:
                  $ref: '#/components/schemas/concernPoints'
      responses:
        '201':
          description: Created
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/AccessForbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /login:
    post:
      operationId: AuthController_login
      summary: Initiate authorization - part of mandatory API
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login'
      responses:
        '200':
          description: The user was found and the password matched.
          content:
            application/json:
              schema:
                $ref : '#/components/schemas/token'
        '401':
          $ref: '#/components/responses/InvalidToken'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /organization:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  organizationId:
                    $ref : '#/components/schemas/orgId'
                  name:
                    $ref : '#/components/schemas/orgName'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/organization/configuration':
    get:
      responses:
        '200': 
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/orgConfiguration'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'      
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/orgConfiguration'
      responses:
        '200': 
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/orgConfiguration'
        
  '/organization/cases':
    get:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                organizationId: 
                  $ref: '#/components/schemas/orgId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  cases:
                    $ref : '#/components/schemas/cases'
              examples:
                one:
                  $ref: '#/components/examples/casesList'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/organization/case':
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                organizationId: 
                  $ref: '#/components/schemas/orgId'

      responses:
        '200':
          description: Creates a new case and associates it with the organization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/caseCreation'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/case':
    delete:
      summary: Delete case record
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                caseId: 
                  $ref: '#/components/schemas/caseId'
      responses:
        '200':
          description: Case deleted
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'        
  '/case/points':
    get:
      summary: Gets patient case record
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                caseId: 
                  $ref: '#/components/schemas/caseId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  concernPoints:
                    $ref: '#/components/schemas/concernPointDb'
              examples:
                one: 
                  $ref : '#/components/examples/concernPoints'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
      security:
        - contactTracer: []
        - admin: []
  '/case/point':
    post:
      summary: Creates a new point of concern to be asssociated with the case
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                caseId:
                  $ref: '#/components/schemas/caseId'
                point:
                  $ref: '#/components/schemas/concernPointDBAdd'
      responses:
        '200':
          description: Patient case updated
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/concernPointDb'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
      security:
        - contactTracer: []
        - admin: []
        
  '/point':
    put:
      summary: Updates an existing point of concern
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/concernPointDb'
      responses:
        '200': 
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/concernPointDb'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      summary: Deletes an existing point of concern
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pointId:
                  $ref: '#/components/schemas/pointId'
      responses:
        '200':
          description: Point was deleted
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'